public struct MigrationCodeGenerator {
    public static func generate(from migrations: [ParsedMigrationFile]) -> String {
        var lines: [String] = []
        lines.append("// Generated by PostgresModels — do not edit")
        lines.append("import Logging")
        lines.append("import PostgresNIO")
        lines.append("")
        lines.append("struct Migrations {")
        lines.append(contentsOf: generateAllArray(migrations))
        lines.append("")
        lines.append(contentsOf: generateRunFunction())
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Private

    private static func generateAllArray(_ migrations: [ParsedMigrationFile]) -> [String] {
        guard !migrations.isEmpty else {
            return ["    private static let all: [(String, String)] = []"]
        }
        var lines: [String] = ["    private static let all: [(String, String)] = ["]
        for m in migrations {
            lines.append("        (\"\(m.name)\", \"\"\"")
            for sqlLine in m.sql.components(separatedBy: "\n") {
                let escaped = sqlLine.replacingOccurrences(of: "\\", with: "\\\\")
                lines.append("            \(escaped)")
            }
            lines.append("            \"\"\"),")
        }
        lines.append("    ]")
        return lines
    }

    private static func generateRunFunction() -> [String] {
        return [
            "    static func run(client: PostgresClient, logger: Logger) async throws {",
            "        try await client.query(\"\"\"",
            "            CREATE TABLE IF NOT EXISTS postgres_models_migrations (",
            "                name TEXT PRIMARY KEY,",
            "                run_at TIMESTAMPTZ NOT NULL DEFAULT now()",
            "            )",
            "            \"\"\", logger: logger)",
            "        for (name, sql) in all {",
            "            let existing = try await client.query(",
            "                \"SELECT 1 FROM postgres_models_migrations WHERE name = \\(name)\",",
            "                logger: logger",
            "            )",
            "            var alreadyRun = false",
            "            for try await _ in existing { alreadyRun = true; break }",
            "            guard !alreadyRun else { continue }",
            "            logger.info(\"Running migration\", metadata: [\"name\": .string(name)])",
            "            try await client.withConnection { conn in",
            "                try await conn.query(\"BEGIN\", logger: logger)",
            "                do {",
            "                    try await conn.query(PostgresQuery(unsafeSQL: sql), logger: logger)",
            "                    try await conn.query(",
            "                        \"INSERT INTO postgres_models_migrations (name) VALUES (\\(name))\",",
            "                        logger: logger",
            "                    )",
            "                    try await conn.query(\"COMMIT\", logger: logger)",
            "                } catch {",
            "                    _ = try? await conn.query(\"ROLLBACK\", logger: logger)",
            "                    throw error",
            "                }",
            "            }",
            "        }",
            "    }",
        ]
    }
}
